apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: gcp-cluster-secret-store 
    
spec:
  provider:
    gcpsm:
      projectID: "fc-it-school-2025" 
      auth:
        secretRef:
          secretAccessKeySecretRef:
            name: "gcp-creds-for-eso"
            key: "credentials.json"   
            namespace: "expressops-dev"