apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: expressops-slack-webhook 
  namespace: expressops-dev 
spec:
  secretStoreRef:
    name: gcp-cluster-secret-store
    kind: ClusterSecretStore 
 
  target:
    name: slack-webhook-secret 
    creationPolicy: Owner  
    template:
      engineVersion: v2
      data:
        SLACK_WEBHOOK_URL: "{{ .slack_webhook_from_gcp }}"
  data:
  - secretKey: slack_webhook_from_gcp
    remoteRef:
      key: slack-webhook-url-expressops-dev 