apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: expressops-slack-webhook 
  namespace: expressops-dev 
 
  secretStoreRef:
    name: gcp-secret-store-expressops
    kind: SecretStore 
 
  target:
    name: slack-webhook-secret 
    creationPolicy: Owner  
    template:
      engineVersion: v2
      data:
        SLACK_WEBHOOK_URL: "{{ printf `{{ .slack_webhook_from_gcp }}` }}"
  data:
  - secretKey: slack_webhook_from_gcp
    remoteRef:
      key: slack-webhook-url-expressops-dev 