apiVersion: v1
data:
  config.yaml: "_meta:\n  type: \"config\"\n  config_version: 2\n\nconfig:\n  dynamic:\n
    \   authc:\n      google_oidc: \n        http_enabled: true\n        transport_enabled:
    false #\n        order: 0 \n        http_authenticator:\n          type: oidc\n
    \         challenge: true \n          config:\n            connect_url: \"https://accounts.google.com/.well-known/openid-configuration\"\n
    \           \n            client_id: \"88527591198-0j3ubv592bsvqn2l5tl49o43mvpeanf6.apps.googleusercontent.com\"\n
    \           client_secret: \"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\"\n   \n            scope:
    \"openid email profile\" \n            \n            kibana_url: \"https://localhost:5601\"
    \n\n            subject_key: 'email' \n    "
  internal_users.yaml: "_meta:\n  type: \"internalusers\"\n  config_version: 2\n\n#
    Default admin/admin user (already exists)\n\nfluentbit_user:\n  hash: \"$2y$12$BVC0XKuoNZVoL75x2TayDO6/hHGxJCZXHzdS87xs34EAFJgVH5o/C\"
    # Hash for --> password\n  description: \"User for Fluent Bit to write logs\"\n\ndashboard_viewer:\n
    \ hash: \"$2y$12$BVC0XKuoNZVoL75x2TayDO6/hHGxJCZXHzdS87xs34EAFJgVH5o/C\" # Hash
    for --> password\n  description: \"User for read-only access to OpenSearch Dashboards\"\n\n#
    To generate hashes:\n# 1. kubectl exec -it opensearch-master-pod-0 -n dav-monitoring
    -- bash  \n# 2. /usr/share/opensearch/plugins/opensearch-security/tools/hash.sh
    -p 'YOUR_SECURE_PASSWORD'\n# 3. Replace with the output\n\n# kubectl create configmap
    opensearch-security-config \\\n#      --from-file=monitoring/opensearch/chart/opensearch-security/internal_users.yaml
    \\\n#      --from-file=monitoring/opensearch/chart/opensearch-security/roles.yaml
    \\\n#      --from-file=monitoring/opensearch/chart/opensearch-security/roles_mapping.yaml
    \\\n#      -n dav-monitoring\n"
  roles.yaml: "_meta:\n  type: \"roles\"\n  config_version: 2\n\nlog_writer:\n  cluster_permissions:\n
    \   - \"cluster_composite_ops\"\n    - \"indices:data/write/bulk*\"\n  index_permissions:\n
    \   - index_patterns:\n        - \"expressops-logs-*\"\n        - \"fluentbit-*\"\n
    \       - \"logs-*\"\n      allowed_actions:\n        - \"indices:data/write*\"\n
    \       - \"indices:create_index\"\n        - \"indices:manage/ilm*\"\n\ndashboard_read_only:\n
    \ cluster_permissions:\n    - \"cluster_composite_ops_ro\"\n  index_permissions:\n
    \   - index_patterns:\n        - \"expressops-logs-*\"\n        - \"fluentbit-*\"\n
    \       - \"logs-*\"\n        - \".kibana*\"\n        - \".opensearch_dashboards*\"\n
    \     allowed_actions:\n        - \"read\"\n        - \"search\"\n        - \"indices:data/read*\"\n
    \ # Tenant permissions <-- for Dashboards multi-tenancy if needed IN FUTURE\n\nos_google_admins_role:\n
    \ cluster_permissions:\n    - \"*\"\n  index_permissions:\n    - index_patterns:\n
    \       - \"*\"\n      allowed_actions:\n        - \"*\"\n  tenant_permissions:\n
    \   - tenant_patterns:\n        - \"*\"\n      allowed_actions:\n        - \"kibana_all_write\"\n
    \ description: \"Rol de administrador para usuarios autenticados vía Google y
    pertenecientes a grupos de administradores designados.\"\n \n"
  roles_mapping.yaml: |-
    _meta:
      type: "rolesmapping"
      config_version: 2

    log_writer:
      reserved: false
      users:
        - "fluentbit_user"
      description: "Maps fluentbit_user to log_writer role"

    dashboard_read_only:
      reserved: false
      users:
        - "dashboard_viewer"
      description: "Maps dashboard_viewer to dashboard_read_only role"

    os_google_admins_role:
      reserved: false
      backend_roles:
        - "gcp_expressops_admins"
      users: []
      description: "Mapea el grupo de Google gcp_expressops_admins al rol interno os_google_admins_role."
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: opensearch-security-configuration
  namespace: dav-monitoring
