serverFiles:
  prometheus.yml:
    scrape_configs:
      - job_name: expressops-local
        scrape_interval: 5s
        metrics_path: /metrics
        static_configs:
          - targets:
            - localhost:8080


server:
  extraScrapeConfigs: |
    - job_name: expressops
      scrape_interval: 15s
      metrics_path: /metrics
      kubernetes_sd_configs:
        - role: service
          namespaces:
            names:
              - default
      relabel_configs:
        - source_labels: [__meta_kubernetes_service_name]
          action: keep
          regex: expressops
        - source_labels: [__meta_kubernetes_pod_container_port_name]
          action: keep
          regex: http|metrics

    - job_name: expressops-static
      static_configs:
        - targets: ['expressops.default.svc.cluster.local:8080']
      metrics_path: /metrics