apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: fake-secret-store
spec:
  provider:
    fake:
      data:
        - key: slack/webhook
          value: '{"slack_webhook_url": "https://hooks.slack.com/services/YOUR/REAL/URL"}' 