apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: expressops-fake-secretstore
spec:
  provider:
    fake:
      data:
        - key: slack/webhook
          value:
            webhook_url: "https://hooks.slack.com/services/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" 