apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: expressops-slack-secret
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: fake-secret-store
    kind: SecretStore
  target:
    name: expressops-secrets
    creationPolicy: Owner
  data:
    - secretKey: SLACK_WEBHOOK_URL
      remoteRef:
        key: slack/webhook
        property: slack_webhook_url 