apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: expressops-slack-external-secret
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: expressops-fake-secretstore
    kind: ClusterSecretStore
  target:
    name: expressops-slack-secret
    creationPolicy: Owner
  data:
    - secretKey: SLACK_WEBHOOK_URL
      remoteRef:
        key: slack/webhook
        property: webhook_url 