apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "expressops.fullname" . }}-env-config
  labels:
    {{- include "expressops.labels" . | nindent 4 }}
data:
  SERVER_PORT: {{ .Values.env.SERVER_PORT | quote }}
  SERVER_ADDRESS: {{ .Values.env.SERVER_ADDRESS | quote }}
  PLUGINS_PATH: {{ .Values.env.PLUGINS_PATH | quote }} 