 {{- if and .Values.slackWebhook.enabled (not .Values.slackWebhook.url) }}
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: {{ include "expressops.fullname" . }}-secret-store
  labels:
    {{- include "expressops.labels" . | nindent 4 }}
spec:
  provider:
    fake:
      data:
        - key: slack/webhook
          value: '{"slack_webhook_url": "https://hooks.slack.com/services/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ication"}'
{{- end }}