{{- if .Values.externalSecrets.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "expressops.fullname" . }}-slack-external-secret
spec:
  refreshInterval: {{ .Values.externalSecrets.refreshInterval | default "1h" | quote }}
  secretStoreRef:
    name: {{ .Values.externalSecrets.secretStore.name }}
    kind: {{ .Values.externalSecrets.secretStore.kind }}
  target:
    name: expressops-slack-secret
    creationPolicy: Owner
  data:
    - secretKey: SLACK_WEBHOOK_URL
      remoteRef:
        key: {{ .Values.externalSecrets.remoteRef.key | default "slack/webhook" }}
        property: {{ .Values.externalSecrets.remoteRef.property | default "webhook_url" }}
{{- end }} 
