{{- if .Values.externalSecrets.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "expressops.fullname" . }}-external-secret
  labels:
    {{- include "expressops.labels" . | nindent 4 }}
spec:
  refreshInterval: {{ .Values.externalSecrets.refreshInterval | default "1h" | quote }}
  secretStoreRef:
    name: {{ .Values.externalSecrets.secretStore.name }}
    kind: {{ .Values.externalSecrets.secretStore.kind }}
  target:
    name: expressops-secrets
    creationPolicy: Owner
  data:
    - secretKey: SLACK_WEBHOOK_URL
      remoteRef:
        key: {{ .Values.externalSecrets.remoteRef.key }}
        {{- if .Values.externalSecrets.remoteRef.version }}
        version: {{ .Values.externalSecrets.remoteRef.version | quote }}
        {{- end }}
        {{- if .Values.externalSecrets.remoteRef.property }}
        property: {{ .Values.externalSecrets.remoteRef.property }}
        {{- end }}
{{- end }} 
