{{- if .Values.secrets.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "expressops.fullname" . }}-external-secret
  labels:
    {{- include "expressops.labels" . | nindent 4 }}
spec:
  refreshInterval: {{ .Values.secrets.refreshInterval | default "1h" | quote }}
  secretStoreRef:
    name: {{ .Values.secrets.gcp.secretStoreName }}
    kind: ClusterSecretStore
  target:
    name: {{ .Values.secrets.secretName }}
    creationPolicy: Owner
  data:
  {{- range .Values.secrets.gcp.secretRefs }}
    - secretKey: {{ .secretKey }}
      remoteRef:
        key: {{ .remoteKey }}
        {{- if .version }}
        version: {{ .version | quote }}
        {{- end }}
        {{- if .property }}
        property: {{ .property }}
        {{- end }}
  {{- end }}
{{- end }} 
