{{- if and .Values.externalSecrets.enabled .Values.gcpSecretManager.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: {{ .Values.externalSecrets.secretStore.name }}
spec:
  provider:
    gcpsm:
      projectID: {{ .Values.gcpSecretManager.projectID }}
      auth:
        secretRef:
          secretAccessKeySecretRef:
            name: {{ include "expressops.fullname" . }}-gcp-sa
            key: sa.json
{{- end }} 