{{- if and .Values.externalSecrets.enabled .Values.gcpSecretManager.enabled }}
{{- if .Values.gcpSecretManager.serviceAccountKey }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "expressops.fullname" . }}-gcp-sa
  labels:
    {{- include "expressops.labels" . | nindent 4 }}
type: Opaque
stringData:
  sa.json: |-
{{ .Values.gcpSecretManager.serviceAccountKey | indent 4 }}
{{- end }}
{{- end }} 