{{- if and .Values.secrets.enabled .Values.secrets.gcp.serviceAccountKey }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "expressops.fullname" . }}-gcp-sa
  labels:
    {{- include "expressops.labels" . | nindent 4 }}
  annotations: #encrypt
    "helm.sh/resource-policy": keep
type: Opaque
stringData:
  sa.json: |-
{{ .Values.secrets.gcp.serviceAccountKey | indent 4 }}
{{- end }} 
