{{- if .Values.secrets.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: {{ .Values.secrets.gcp.secretStoreName }}
spec:
  provider:
    gcpsm:
      projectID: {{ .Values.secrets.gcp.projectID }}
      auth:
        secretRef:
          secretAccessKeySecretRef:
            name: {{ include "expressops.fullname" . }}-gcp-sa
            key: sa.json
{{- end }} 