apiVersion: v2
name: opensearch
description: Helm chart for deploying OpenSearch and OpenSearch Dashboards to Kubernetes
type: application
version: 0.1.0
appVersion: "2.15.0"
keywords:
  - opensearch
  - elasticsearch
  - dashboards
  - logging
  - search
maintainers:
  - name: ExpressOps Team
home: https://opensearch.org/
icon: https://opensearch.org/assets/opensearch-logo-themed.svg
kubeVersion: ">=1.19.0-0" 