clusterName: "expressops-opensearch"
nodeGroup: "master"

security:
  enabled: true
  passwordSecret: ""
  adminUsername: "admin"
  adminPassword: ""
  tls:
    enabled: true
    generateCertificates: true

master:
  replicas: 1
  heapSize: "512m"
  resources:
    requests:
      cpu: "500m" 
      memory: "1Gi"
    limits:
      cpu: "1000m"
      memory: "1Gi"
  persistence:
    enabled: true
    storageClass: ""
    size: 8Gi

data:
  replicas: 1
  heapSize: "1g"
  resources:
    requests:
      cpu: "500m"
      memory: "2Gi"
    limits:
      cpu: "1000m" 
      memory: "2Gi"
  persistence:
    enabled: true
    storageClass: ""
    size: 20Gi

dashboards:
  enabled: true
  replicas: 1
  resources:
    requests:
      cpu: "100m"
      memory: "500Mi"
    limits:
      cpu: "500m"
      memory: "1Gi"
  service:
    type: ClusterIP

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: opensearch.example.com
      paths:
        - path: /
          pathType: Prefix
  tls: []

serviceAccount:
  create: true
  name: ""