apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "expressops-chart.fullname" . }}-config
  labels:
    {{- include "expressops-chart.labels" . | nindent 4 }}
data:
  config.yaml: |
    logging:
      level: info
      format: text

    server:
      port: {{ .Values.service.targetPort }}
      address: 0.0.0.0
      timeoutSeconds: 4

      http:
        protocolVersion: 2

    plugins:
      - name: slack-notifier
        path: plugins/slack/slack.so
        type: notification
        config:
          webhook_url: $SLACK_WEBHOOK_URL

      - name: health-check-plugin
        path: plugins/healthcheck/health_check.so
        type: health
        config: {}

      - name: sleep-plugin
        path: plugins/sleep/sleep_plugin.so
        type: test
        config:
          duration_seconds: ${SLEEP_DURATION:-10}

      # - name: kube-health-plugin
      #   path: plugins/kubehealth/kube_health.so
      #   type: k8s
      #   config: {}

      - name: test-print-plugin
        path: plugins/testprint/testprint.so
        type: test
        config: {}

      - name: formatter-plugin
        path: plugins/formatters/health_alert_formatter.so
        type: utils
        config: {}

      - name: permissions-plugin
        path: plugins/permissions/permissions.so
        type: management
        config:
          base_directory: "/var/data/projects"
          default_username: "example-user"
          default_permissions: "rwx"
          default_paths:
            - "it-school-2025-2"
            - "it-school-2025-3"

      - name: user-creation-plugin
        path: plugins/usercreation/user_creation.so
        type: management
        config:
          default_username: "example-user"
          default_groups:
            - "users"
            - "developers"
          default_homedir_base: "/home"
          default_shell: "/bin/bash"

    flows:
      - name: incident-flow
        description: "Notify the team when an incident occurs"
        pipeline:
          - pluginRef: slack-notifier

      - name: healthz
        description: "Health check"
        customHandler: healthCheckDetailed
        pipeline:
          - pluginRef: health-check-plugin
          - pluginRef: formatter-plugin
          - pluginRef: slack-notifier

      - name: test-context
        description: "Test the context timeout"
        customHandler: contextTimeoutTest
        pipeline:
          - pluginRef: sleep-plugin

      - name: dr-house
        description: "Check the health of the cluster"
        pipeline:
          - pluginRef: health-check-plugin
          - pluginRef: formatter-plugin
          - pluginRef: test-print-plugin

      - name: alert-flow
        description: "Health check with notification"
        pipeline:
          - pluginRef: health-check-plugin
          - pluginRef: formatter-plugin
          - pluginRef: slack-notifier

      - name: create-user
        description: "Create a user in GCP"
        pipeline:
          - pluginRef: user-creation-plugin
          - pluginRef: slack-notifier

      - name: set-permissions
        description: "Change permissions for a specific user on specified paths in GCP"
        pipeline:
          - pluginRef: permissions-plugin
          - pluginRef: slack-notifier

      - name: user-onboarding
        description: "Complete onboarding process: create user and set permissions"
        pipeline:
          - pluginRef: user-creation-plugin
          - pluginRef: slack-notifier
          - pluginRef: permissions-plugin
          - pluginRef: slack-notifier
