apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Values.externalSecret.name }}
  labels:
    {{- include "expressops-chart.labels" . | nindent 4 }}

spec:
 
  secretStoreRef:
    name: {{ .Values.secretStore.name }}
    kind: SecretStore 
 
  target:
    name: {{ .Values.slackSecretName }}
    creationPolicy: Owner  
    template:
      engineVersion: v2
      data:
        SLACK_WEBHOOK_URL: "{{ .slack_webhook_from_gcp }}"
  data:
  - secretKey: slack_webhook_from_gcp
    remoteRef:
      key: {{ .Values.externalSecret.gcpSecretName }}