# expressops-chart/templates/servicemonitor.yaml
{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "expressops-chart.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "expressops-chart.labels" . | nindent 8 }}
        release: prometheus-d
spec:
  selector:
    matchLabels:
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/name: {{ include "expressops-chart.name" . }}
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  endpoints:
  - port: http
    path: /metrics
{{- end }}