apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Release.Name }}-master
  labels:
    app: {{ .Release.Name }}-opensearch
    role: master
    {{- include "opensearch.labels" . | nindent 4 }}
spec:
  serviceName: {{ .Release.Name }}-master
  replicas: {{ .Values.master.replicas }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-opensearch
      role: master
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-opensearch
        role: master
    spec:
      serviceAccountName: {{ include "opensearch.serviceAccountName" . }}
      securityContext:
        fsGroup: 1000
      initContainers:
        - name: init-sysctl
          image: busybox:1.34.1
          command: ["sysctl", "-w", "vm.max_map_count=262144"]
          securityContext:
            privileged: true
      containers:
        - name: opensearch
          image: "opensearchproject/opensearch:{{ .Values.appVersion }}"
          securityContext:
            runAsUser: 1000
          env:
            - name: node.name
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: discovery.seed_hosts
              value: "{{ .Release.Name }}-master-headless"
            - name: cluster.initial_master_nodes
              value: "{{ .Release.Name }}-master-0"
            - name: cluster.name
              value: {{ .Values.clusterName }}
            - name: node.master
              value: "true"
            - name: node.data
              value: "false"
            - name: OPENSEARCH_JAVA_OPTS
              value: "-Xms{{ .Values.master.heapSize }} -Xmx{{ .Values.master.heapSize }}"
            - name: DISABLE_SECURITY_PLUGIN
              value: "{{ if .Values.security.enabled }}false{{ else }}true{{ end }}"
          ports:
            - name: http
              containerPort: 9200
            - name: transport
              containerPort: 9300
          livenessProbe:
            tcpSocket:
              port: transport
            initialDelaySeconds: 120
            periodSeconds: 10
          readinessProbe:
            httpGet:
              scheme: HTTP
              path: /_cluster/health?local=true
              port: http
            initialDelaySeconds: 120
            periodSeconds: 10
          resources:
            {{- toYaml .Values.master.resources | nindent 12 }}
          volumeMounts:
            - name: data
              mountPath: /usr/share/opensearch/data
  {{- if .Values.master.persistence.enabled }}
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        {{- if .Values.master.persistence.storageClass }}
        storageClassName: {{ .Values.master.persistence.storageClass }}
        {{- end }}
        resources:
          requests:
            storage: {{ .Values.master.persistence.size }}
  {{- else }}
      volumes:
        - name: data
          emptyDir: {}
  {{- end }} 