apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-master
  labels:
    app: {{ .Release.Name }}-opensearch
    role: master
    {{- include "opensearch.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 9200
      targetPort: http
      protocol: TCP
      name: http
    - port: 9300
      targetPort: transport
      protocol: TCP
      name: transport
  selector:
    app: {{ .Release.Name }}-opensearch
    role: master

---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-master-headless
  labels:
    app: {{ .Release.Name }}-opensearch
    role: master
    {{- include "opensearch.labels" . | nindent 4 }}
spec:
  clusterIP: None
  ports:
    - port: 9200
      targetPort: http
      protocol: TCP
      name: http
    - port: 9300
      targetPort: transport
      protocol: TCP
      name: transport
  selector:
    app: {{ .Release.Name }}-opensearch
    role: master 