apiVersion: apps/v1
kind: Deployment
metadata:
  name: expressops
  namespace: expressops-dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: expressops
  template:
    metadata:
      labels:
        app: expressops
    spec:
      containers:
      - name: expressops
        image: ciberegaliz/expressops:latest
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: "500m"
            memory: "512Mi"
          requests:
            cpu: "100m"
            memory: "128Mi"

        envFrom:
        - secretRef:
            name: slack-webhook-secret
        - configMapRef:
            name: expressops-env    

        volumeMounts:
        - name: config-volume
          mountPath: /app/config.yaml
          subPath: config.yaml

        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 5
          timeoutSeconds: 2
          periodSeconds: 10
          failureThreshold: 3

        readinessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 2
          periodSeconds: 5

      volumes:
      - name: config-volume
        configMap:
          name: expressops-config

---
apiVersion: v1
kind: Service
metadata:
  name: expressops
  namespace: expressops-dev
spec:
  type: ClusterIP
  selector:
    app: expressops
  ports:
  - port: 80
    targetPort: 8080
