apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: gcp-secret-manager 
  namespace: expressops-dev 
spec:
  provider:
    gcpsm: 
      projectID: "fc-it-school-2025"

      
      # NO especificamos 'auth' aquí.
      # Al omitir la sección 'auth', ESO intentará usar las credenciales
      # ambientales disponibles en el pod donde corre (Application Default Credentials - ADC).
      # En una VM de GCE, ADC usa la Service Account del nodo.