# Configuración mínima para values.yaml
replicas: 1
clusterName: opensearch
nodeGroup: master

image:
  repository: opensearchproject/opensearch
  imagePullPolicy: IfNotPresent
  tag: "3.0.0"

opensearchJavaOpts: "-Xms1g -Xmx1g"

config:
  opensearch.yml: |
    discovery.type: single-node
    network.host: 0.0.0.0
    plugins.security.disabled: true
    plugins.security.ssl.http.enabled: false
    plugins.security.ssl.transport.enabled: false

resources:
  requests:
    cpu: "0.5"
    memory: "512Mi"
  limits:
    cpu: "2"
    memory: "2Gi"

nodeSelector:
 role: opensearch-node

persistence:
  enabled: false

singleNode: true

service:
  type: ClusterIP
  httpPort: 9200
  metricsPort: 9600

imagePullSecrets:
  - name: gcp-creds-for-eso
