  replicas: 1
  clusterName: opensearch
  nodeGroup: master

  image:
    repository: europe-west1-docker.pkg.dev/fc-it-school-2025/opensearch-repo/opensearch:3.0.0
    imagePullPolicy: IfNotPresent
    tag: "3.0.0"

  opensearchJavaOpts: "-Xms2g -Xmx2g"

  config:
    opensearch.yml: |
      discovery.type: single-node
      plugins.security.ssl.http.enabled: true
      plugins.security.ssl.transport.enabled: true
      network.host: 0.0.0.0
      plugins.security.disabled: false

  extraEnvs:
    - name: OPENSEARCH_INITIAL_ADMIN_PASSWORD
      valueFrom:
        secretKeyRef:
          name: opensearch-admin-secret
          key: OPENSEARCH_INITIAL_ADMIN_PASSWORD

  resources:
    requests:
      cpu: "2"
      memory: "2Gi"
    limits:
      cpu: "4"
      memory: "4Gi"

  nodeSelector:
   role: opensearch-node

  persistence:
    enabled: true
    size: "50Gi"
    accessModes:
      - ReadWriteOnce

  service:
    type: ClusterIP
    httpPort: 9200
    metricsPort: 9600

  singleNode: true

  security:
    enabled: true
    ssl:
      transport:
        enabled: true
      http:
        enabled: true

  imagePullSecrets:
    - name: gcp-creds-for-eso
