apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentbit-config
  namespace: dav-monitoring
  labels:
    app.kubernetes.io/name: fluentbit
data:
  fluent-bit.conf: |
    [SERVICE]
        Flush         1
        Daemon        Off
        Log_Level     info
        Parsers_File  parsers.conf
        HTTP_Server   On
        HTTP_Listen   0.0.0.0
        HTTP_Port     2020

    @INCLUDE inputs.conf
    @INCLUDE filters.conf
    @INCLUDE outputs.conf

  inputs.conf: |
    [INPUT]
        Name              tail
        Path              /var/log/pods/default_expressops*/*/*.log
        Tag               expressops
        Parser            cri
        DB                /fluent-bit/tail_db/flb_kube.db
        Mem_Buf_Limit     5MB
        Skip_Long_Lines   On
        Refresh_Interval  10

  filters.conf: |
    [FILTER]
        Name                modify
        Match               expressops
        Add                 application expressops
        Add                 environment production
    
  outputs.conf: |
    [OUTPUT]
        Name              opensearch
        Match             expressops
        Host              opensearch-cluster-master.dav-monitoring.svc.cluster.local
        Port              9200
        Index             expressops-logs
        Logstash_Format   On
        Logstash_Prefix   expressops-logs
        Suppress_Type_Name On
        HTTP_User         ""
        HTTP_Passwd       ""
        tls               Off
        tls.verify        Off
        Retry_Limit       5

  parsers.conf: |
    [PARSER]
        Name        cri
        Format      regex
        Regex       ^(?<time>[^ ]+) (?<stream>stdout|stderr) (?<logtag>[^ ]*) (?<log>.*)$
        Time_Key    time
        Time_Format %Y-%m-%dT%H:%M:%S.%L%z

    [PARSER]
        Name        docker
        Format      json
        Time_Key    time
        Time_Format %Y-%m-%dT%H:%M:%S.%L%z
