apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: fluentbit-dual
  namespace: dav-monitoring
  labels:
    app.kubernetes.io/name: fluentbit-dual
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: fluentbit-dual
  template:
    metadata:
      labels:
        app.kubernetes.io/name: fluentbit-dual
    spec:
      imagePullSecrets:
      - name: gcp-creds-for-eso
      serviceAccountName: fluentbit-dual
      terminationGracePeriodSeconds: 10
      hostNetwork: false
      dnsPolicy: ClusterFirst
      containers:
      - name: fluentbit
        image: fluent/fluent-bit:2.2.2
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 2020
          name: http
        livenessProbe:
          httpGet:
            path: /
            port: 2020
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /api/v1/health
            port: 2020
          initialDelaySeconds: 5
          periodSeconds: 5
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: OPENSEARCH_USER
          valueFrom:
            secretKeyRef:
              name: opensearch-credentials-secure
              key: username
        - name: OPENSEARCH_PASSWORD
          valueFrom:
            secretKeyRef:
              name: opensearch-credentials-secure
              key: password
        resources:
          limits:
            memory: 512Mi
            cpu: 200m
          requests:
            cpu: 100m
            memory: 128Mi
        volumeMounts:
        - name: config
          mountPath: /fluent-bit/etc/
        - name: fluentbit-tail-db
          mountPath: /fluent-bit/tail_db
        - name: varlog
          mountPath: /var/log
          readOnly: true
        - name: varlibkubeletpods
          mountPath: /var/lib/kubelet/pods
          readOnly: true
        - name: varlibcontainers
          mountPath: /var/lib/docker/containers
          readOnly: true
      volumes:
      - name: config
        configMap:
          name: fluentbit-config-dual
      - name: fluentbit-tail-db
        hostPath:
          path: /var/lib/fluentbit/tail_db
          type: DirectoryOrCreate
          # create the directory if it doesn't exist
      - name: varlog
        hostPath:
          path: /var/log
      - name: varlibkubeletpods
        hostPath:
          path: /var/lib/kubelet/pods
      - name: varlibcontainers
        hostPath:
          path: /var/lib/docker/containers 