apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: fluentbit
  namespace: dav-monitoring
  labels:
    app.kubernetes.io/name: fluentbit
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: fluentbit
  template:
    metadata:
      labels:
        app.kubernetes.io/name: fluentbit
    spec:
      serviceAccountName: fluentbit
      terminationGracePeriodSeconds: 10
      hostNetwork: false
      dnsPolicy: ClusterFirst
      containers:
      - name: fluentbit
        image: fluent/fluent-bit:2.2.2
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 2020
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: OPENSEARCH_USER
          valueFrom:
            secretKeyRef:
              name: opensearch-credentials
              key: username
        - name: OPENSEARCH_PASSWORD
          valueFrom:
            secretKeyRef:
              name: opensearch-credentials
              key: password
        resources:
          limits:
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 128Mi
        volumeMounts:
        - name: config
          mountPath: /fluent-bit/etc/
        - name: fluentbit-tail-db
          mountPath: /fluent-bit/tail_db
        - name: varlog
          mountPath: /var/log
        - name: varlibkubeletpods
          mountPath: /var/lib/kubelet/pods
          readOnly: true
      volumes:
      - name: config
        configMap:
          name: fluentbit-config
      - name: fluentbit-tail-db
        hostPath:
          path: /var/lib/fluentbit/tail_db
          type: DirectoryOrCreate
      - name: varlog
        hostPath:
          path: /var/log
      - name: varlibkubeletpods
        hostPath:
          path: /var/lib/kubelet/pods