apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: juicefs-gcs-redis
provisioner: csi.juicefs.com
parameters:
# Secret para obtener el nombre del volumen y la URL de metadatos (Redis)
  csi.storage.k8s.io/provisioner-secret-name: "juicefs-meta-conf"
  csi.storage.k8s.io/provisioner-secret-namespace: "expressops-dev"

# Secret para las credenciales de GCS que usará el nodo CSI para montar
  csi.storage.k8s.io/node-publish-secret-name: "juicefs-gcs-manager-credentials"
  csi.storage.k8s.io/node-publish-secret-namespace: "expressops-dev"

  # Opciones de montaje adicionales para JuiceFS (opcionales pero recomendadas).
  
  juicefs/mount-options: "metrics=0.0.0.0:9567, cache-dir=/var/jfsCache/{{.PV.name}},cache-size=2048" # Para exponer métricas de Prometheus y 2GB de caché

reclaimPolicy: Retain
allowVolumeExpansion: true
volumeBindingMode: Immediate