# juicefs-csi-driver-values.yaml

# Por defecto, el chart de JuiceFS CSI Driver crea las ServiceAccounts,
# ClusterRoles y ClusterRoleBindings necesarios para su operación.
# No es necesario especificar credenciales aquí para el montaje del volumen
# pre-formateado, ya que se gestionarán a través de la StorageClass
# y los secrets referenciados (juicefs-meta-conf).

# Puedes ajustar los recursos para los pods del driver si es necesario,
# pero los valores por defecto suelen ser adecuados para empezar.
# controller:
#   resources:
#     limits:
#       cpu: 200m
#       memory: 200Mi
#     requests:
#       cpu: 100m
#       memory: 100Mi
# node:
#   resources:
#     limits:
#       cpu: 1000m # Puede necesitar más CPU si el uso es intensivo
#       memory: 1Gi   # Y más memoria para el caché en RAM del cliente JuiceFS
#     requests:
#       cpu: 100m
#       memory: 100Mi

# Si quieres habilitar el caché en disco para los nodos JuiceFS (mejora el rendimiento)
# Esto se configura globalmente aquí o por StorageClass/PV.
# Es más flexible configurarlo por StorageClass o PV si tienes diferentes necesidades.
# Ejemplo:
# mountPod:
#   mountOptions:
#     cacheDir: "/var/jfsCache" # Directorio en el hostPath del nodo o un emptyDir
#     cacheSize: 10240 # Tamaño del caché en MiB (10GiB)