apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus-data-juicefs
  namespace: monitoring
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: juicefs-gcs-redis