apiVersion: v1
kind: Secret
metadata:
  name: expressops-secrets
type: Opaque
stringData:
  SLACK_WEBHOOK_URL: "https://hooks.slack.com/services/YOUR/WEBHOOK/URL"
  # Add other secrets here if needed
  # IN THE FUTURE SECRETS WILL BE STORED IN A EXTERNAL SECRET OPERATOR