clusterName: "default"
nodeGroup: "master"

replicas: 1
minimumMasterNodes: 1


# depends on java
opensearchJavaOpts: "-Xmx512m -Xms512m"

persistence:
  enabled: true
  size: "8Gi"

service:
  type: ClusterIP

config:
  opensearch.yml: |
    cluster.name: ${CLUSTER_NAME}
    node.name: ${NODE_NAME}
    
    plugins.security.disabled: false
    
    thread_pool.write.queue_size: 1000
    indices.memory.index_buffer_size: 10%
    indices.queries.cache.size: 5%
    
    cluster.routing.allocation.disk.threshold_enabled: true
    cluster.routing.allocation.disk.watermark.low: "90%"
    cluster.routing.allocation.disk.watermark.high: "95%"

securityConfig:
  enabled: true
  adminCredentials:
    username: admin
    password: admin

networkHost: "0.0.0.0"

securityContext:
  runAsUser: 1000
  fsGroup: 1000

prometheus:
  monitor:
    enabled: true

tolerations:
  - key: "node.kubernetes.io/memory-pressure"
    operator: "Exists"
    effect: "NoExecute"
    tolerationSeconds: 300
  
antiAffinity: "soft"

readinessProbe:
  initialDelaySeconds: 60
  timeoutSeconds: 20

livenessProbe:
  initialDelaySeconds: 120
  timeoutSeconds: 20 