# This file is kept for reference if a manifest-based approach is preferred for Fluent Bit.
# The current Terraform configuration decomposes this into individual Kubernetes resources.
apiVersion: v1
kind: ServiceAccount
metadata:
  name: fluentbit
  namespace: dav-monitoring # Replace with var.namespace if templated
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: fluentbit
rules:
  - apiGroups: [""]
    resources:
      - namespaces
      - pods
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: fluentbit
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: fluentbit
subjects:
  - kind: ServiceAccount
    name: fluentbit
    namespace: dav-monitoring # Replace with var.namespace
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentbit-config
  namespace: dav-monitoring # Replace with var.namespace
  labels:
    app.kubernetes.io/name: fluentbit
data:
  fluent-bit.conf: |-
    [SERVICE]
        Flush         1
        Daemon        Off
        Log_Level     info
        Parsers_File  parsers.conf
        HTTP_Server   On
        HTTP_Listen   0.0.0.0
        HTTP_Port     2020

    @INCLUDE inputs.conf
    @INCLUDE filters.conf
    @INCLUDE outputs.conf

  inputs.conf: |-
    [INPUT]
        Name              tail
        Tag               kube.*
        Path              /var/log/containers/*.log
        Parser            cri
        DB                /var/log/flb_kube.db
        Mem_Buf_Limit     5MB
        Skip_Long_Lines   On
        Refresh_Interval  10

  filters.conf: |-
    [FILTER]
        Name                kubernetes
        Match               kube.*
        Kube_URL            https://kubernetes.default.svc:443
        Kube_CA_File        /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        Kube_Token_File     /var/run/secrets/kubernetes.io/serviceaccount/token
        Kube_Tag_Prefix     kube.
        Merge_Log           On
        K8S-Logging.Parser  On
        K8S-Logging.Exclude Off

  outputs.conf: |-
    [OUTPUT]
        Name            opensearch
        Match           *
        Host            opensearch-cluster-master # Replace with var.opensearch_host
        Port            9200 # Replace with var.opensearch_port
        HTTP_User       ${OPENSEARCH_USERNAME}
        HTTP_Passwd     ${OPENSEARCH_PASSWORD}
        Index           logs
        Suppress_Type_Name On
        tls             On
        tls.verify      Off

  parsers.conf: |-
    [PARSER]
        Name   cri
        Format regex
        Regex  ^(?<time>[^ ]+) (?<stream>stdout|stderr) (?<logtag>[^ ]*) (?<log>.*)$
        Time_Key    time
        Time_Format %Y-%m-%dT%H:%M:%S.%L%z

---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: fluentbit
  namespace: dav-monitoring # Replace with var.namespace
  labels:
    app.kubernetes.io/name: fluentbit
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: fluentbit
  template:
    metadata:
      labels:
        app.kubernetes.io/name: fluentbit
    spec:
      serviceAccountName: fluentbit
      containers:
      - name: fluentbit
        image: fluent/fluent-bit:2.1.8 # Replace with var.fluentbit_image_tag
        imagePullPolicy: IfNotPresent
        env:
          - name: OPENSEARCH_USERNAME
            valueFrom:
              secretKeyRef:
                name: opensearch-credentials-secure # Replace with var.credentials_name
                key: username
          - name: OPENSEARCH_PASSWORD
            valueFrom:
              secretKeyRef:
                name: opensearch-credentials-secure # Replace with var.credentials_name
                key: password
        volumeMounts:
        - name: config
          mountPath: /fluent-bit/etc/
        - name: varlog
          mountPath: /var/log
        - name: varlibcontainers
          mountPath: /var/lib/docker/containers
          readOnly: true
        - name: etcmachineid
          mountPath: /etc/machine-id
          readOnly: true
        ports:
        - name: http
          containerPort: 2020
      volumes:
      - name: config
        configMap:
          name: fluentbit-config
      - name: varlog
        hostPath:
          path: /var/log
      - name: varlibcontainers
        hostPath:
          path: /var/lib/docker/containers
      - name: etcmachineid
        hostPath:
          path: /etc/machine-id
          type: File 