replicas: 1
clusterName: opensearch
nodeGroup: master

image:
  repository: opensearchproject/opensearch # Changed from private repo for generality
  imagePullPolicy: IfNotPresent
  tag: "${opensearch_image_tag}"

opensearchJavaOpts: "-Xms1g -Xmx1g"

config:
  opensearch.yml: |
    discovery.type: single-node # will be changed to cluster-mode in the future :(
    network.host: 0.0.0.0
    
    plugins.security.disabled: false
    
    plugins.security.ssl.http.enabled: true
    plugins.security.ssl.transport.enabled: true
    
    plugins.security.ssl.http.pemcert_filepath: /usr/share/opensearch/config/certs/node.pem
    plugins.security.ssl.http.pemkey_filepath: /usr/share/opensearch/config/certs/node-key.pem
    plugins.security.ssl.http.pemtrustedcas_filepath: /usr/share/opensearch/config/certs/root-ca.pem
    plugins.security.ssl.transport.pemcert_filepath: /usr/share/opensearch/config/certs/node.pem
    plugins.security.ssl.transport.pemkey_filepath: /usr/share/opensearch/config/certs/node-key.pem
    plugins.security.ssl.transport.pemtrustedcas_filepath: /usr/share/opensearch/config/certs/root-ca.pem
    
    plugins.security.allow_default_init_securityindex: true
    
    plugins.query.datasources.encryption.masterkey: "A1B2C3D4E5F6G7H8" # Consider making this a variable

resources:
  requests:
    cpu: "0.5"
    memory: "512Mi"
  limits:
    cpu: "2"
    memory: "2Gi"

nodeSelector:
  role: opensearch-node 

persistence:
  enabled: true
  storageClass: "juicefs-gcs-redis-canonica" # we have this storage class in GCP
  size: 10Gi

singleNode: true

service:
  type: ClusterIP 
  httpPort: 9200
  metricsPort: 9600

extraVolumes:
  - name: certs
    secret:
      secretName: ${secrets_name} 

extraVolumeMounts:
  - name: certs
    mountPath: /usr/share/opensearch/config/certs
    readOnly: true

extraEnvs:
  - name: OPENSEARCH_USERNAME
    valueFrom:
      secretKeyRef:
        name: ${credentials_name} 
        key: username
  - name: OPENSEARCH_PASSWORD
    valueFrom:
      secretKeyRef:
        name: ${credentials_name} 
        key: password

# imagePullSecrets: # dont know if will work
#   - name: opensearch-registry-creds

extraPlugins: 
  - opensearch-performance-analyzer
  - opensearch-knn
  - opensearch-saml
  - opensearch-alerting
  - opensearch-anomaly-detection
  - opensearch-index-management
  - opensearch-sql
  - opensearch-prometheus 
  - opensearch-machine-learning
  - opensearch-observability
  - opensearch-reports
  - opensearch-gantt-chart
  - opensearch-visualizations 