# expressops-chart/templates/servicemonitor.yaml
{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "expressops-chart.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "expressops-chart.labels" . | nindent 8 }}
        release: prometheus-d
spec:
  selector:
    matchLabels:
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/name: {{ include "expressops-chart.name" . }}
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  endpoints:
  - port: http
    path: /metrics
    interval: {{ .Values.serviceMonitor.interval }}
#  Esto añade la etiqueta 'rollouts_pod_template_hash' de los pods a las métricas scrapeadas,
# permitiendo a PromQL filtrar por la versión canary o estable:
    metricRelabelings:
    - sourceLabels: [_meta_kubernetes_pod_label_rollouts_pod_template_hash]
      targetLabel: rollouts_pod_template_hash
      action: replace
{{- end }}