deploymentMode: SingleBinary
loki:
  auth_enabled: false
  commonConfig:
    replication_factor: 1
  storage:
    type: filesystem # JuiceFS se presenta como un filesystem al pod
  schemaConfig:
    configs:
      - from: "2024-04-01"
        store: tsdb
        object_store: filesystem
        schema: v13
        index:
          prefix: loki_index_
          period: 24h
singleBinary:
  replicas: 1
  persistence:
    enabled: true
    storageClassName: "juicefs-gcs-redis-canonica"
    size: 10Gi
    accessModes:
      - ReadWriteOnce # Adecuado para SingleBinary
  # Configuración de seguridad para permitir a Loki escribir en el volumen JuiceFS
  # El usuario por defecto de Loki en el chart es 10001
  podSecurityContext:
    fsGroup: 10001
  securityContext:
    runAsUser: 10001
    runAsGroup: 10001

gateway:
  enabled: true

read:
  replicas: 0
write:
  replicas: 0
backend:
  replicas: 0

# Opcional: Habilitar serviceMonitor si usas Prometheus Operator
monitoring:
  selfMonitoring:
    enabled: false
    grafanaAgent:
      installOperator: false
  serviceMonitor:
    enabled: true # Para que Prometheus pueda scrapear Loki
  lokiCanary:
    enabled: false