# juicefs-csi-driver-values.yaml

# Por defecto, el chart de JuiceFS CSI Driver crea las ServiceAccounts,
# ClusterRoles y ClusterRoleBindings necesarios para su operación.
# No es necesario especificar credenciales aquí para el montaje del volumen
# pre-formateado, ya que se gestionarán a través de la StorageClass
# y los secrets referenciados (juicefs-meta-conf).

# Puedes ajustar los recursos para los pods del driver si es necesario,
# pero los valores por defecto suelen ser adecuados para empezar.
# juicefs-csi-driver-values.yaml

juicefs-csi-driver:
  # Imagen principal del driver JuiceFS
  image:
    repository: juicedata/juicefs-csi-driver
    tag: "v0.23.4"
    pullPolicy: "IfNotPresent"

  # Configuración para el controlador CSI
  controller:
    resources:
      requests:
        cpu: 50m
        memory: 256Mi
      limits:
        memory: 256Mi
    # Sidecars del controlador
    provisioner:
      image:
        repository: registry.k8s.io/sig-storage/csi-provisioner
        tag: "v3.5.0"
        pullPolicy: "IfNotPresent"
    resizer:
      image:
        repository: registry.k8s.io/sig-storage/csi-resizer
        tag: "v1.8.0"
        pullPolicy: "IfNotPresent"
    livenessProbe:
      image:
        repository: registry.k8s.io/sig-storage/livenessprobe
        tag: "v2.10.0"
        pullPolicy: "IfNotPresent"
    serviceAccount:
      name: "juicefs-csi-controller-sa-v2"

  # Configuración para los pods de nodo (CSI node) (Daemonset)
  node:
    resources:
      requests:
        cpu: 50m
        memory: 512Mi
      limits:
        memory: 512Mi
    # Sidecars del nodo
    driverRegistrar:
      image:
        repository: registry.k8s.io/sig-storage/csi-node-driver-registrar
        tag: "v2.8.0"
        pullPolicy: "IfNotPresent"
    livenessProbe:
      image:
        repository: registry.k8s.io/sig-storage/livenessprobe
        tag: "v2.10.0"
        pullPolicy: "IfNotPresent"
    serviceAccount:
      name: "juicefs-csi-node-sa-v2"

  dashboard:
    serviceAccount:
      name: "juicefs-csi-dashboard-sa-v2"

  # Patch dinámico para los Mount Pods (volúmenes JuiceFS)
  globalConfig:
    mountPodPatch:
      - resources:
          requests:
            cpu: 75m
            memory: 1.5Gi
          limits:
            memory: 1.5Gi

# Si quieres habilitar el caché en disco para los nodos JuiceFS (mejora el rendimiento)
# Esto se configura globalmente aquí o por StorageClass/PV.
# Es más flexible configurarlo por StorageClass o PV si tienes diferentes necesidades.
# Ejemplo:
# mountPod:
#   mountOptions:
#     cacheDir: "/var/jfsCache" # Directorio en el hostPath del nodo o un emptyDir
#     cacheSize: 10240 # Tamaño del caché en MiB (10GiB)