apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-juicefs-pvc
  namespace: expressops-dev
spec:
  storageClassName: juicefs-gcs-redis-canonica
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Mi
