apiVersion: v1
kind: ConfigMap
metadata:
  name: logstash-config
  namespace: dav-monitoring
data:
  logstash.yml: |
    http.host: "0.0.0.0"
    path.config: /usr/share/logstash/pipeline
  logstash.conf: |
    input {
      beats {
        port => 5044
      }
    }
    output {
      elasticsearch {
        hosts => ["http://opensearch-cluster-master.dav-monitoring.svc.cluster.local:9200"]
        index => "logs-%{+YYYY.MM.dd}"
      }
    }
