apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster-secrets
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/freepik-company/expressops.git
    path: k3s/infrastructure/secret-base-config
    targetRevision: rama_nacho
  destination:
    server: 'https://kubernetes.default.svc'

    namespace: expressops-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
