# gitops-argocd/apps/05-expressops-app.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: expressops
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "10"
  finalizers:
    - resources-finalizer.argocd.argoproj.io

spec:
  project: default
  source:

    repoURL: git@github.com:freepik-company/expressops.git
    targetRevision: rama_nacho
    path: k3s/apps/expressops-app/expressops-chart

    helm:
      releaseName: expressops

      valueFiles:
        - values.yaml

  destination:
    server: 'https://kubernetes.default.svc'
 
    namespace: expressops-dev
  syncPolicy:
    automated:
      prune: true    # Permite a ArgoCD eliminar recursos gestionados que ya no están en Git
      selfHeal: true # Permite a ArgoCD revertir cambios hechos directamente en el clúster
    syncOptions:
      - CreateNamespace=true # Crea el namespace de destino si no existe
      # - RespectIgnoreDifferences=true # Si usas ignoreDifferences