# Paso 1: Parsear este fichero yaml y que se guarde en un struct para acceder a los campos
logging:
  level: info
  format: json

# Paso 2: Levantar un server para probar
server:
  port: 8080
  address: 0.0.0.0

  http:
    protocolVersion: 2

  # Paso 3: Construir un plugin que se compile como .so
plugins:
  - name: slack-notifier
    path: plugins/slack/slack.so
    type: notification
    config: {}
      

  - name: health-check-plugin
    path: plugins/healthcheck/health_check.so
    type: health
    config: {}

  - name: sleep-plugin
    path: plugins/sleep/sleep_plugin.so
    type: test
    config: {}
 
  - name: kube-health-plugin
    path: plugins/kubehealth/kube_health.so
    type: k8s
    config: {}

  - name: test-print-plugin
    path: plugins/testprint/testprint.so
    type: test
    config: {}

  - name: formatter-plugin
    path: plugins/formatters/health_alert_formatter.so
    type: utils
    config: {}

 # Paso 4: Crear un pipeline que ejecute los plugins que se han cargado en el paso 3 y que se ejecuten en el orden que se han definido en el fichero yaml   
flows:
  - name: incident-flow
    pipeline:
      - pluginRef: slack-notifier
        parameters:
          message: "¡Alerta de prueba!"
          channel: "#alerts"
          severity: "high"

  - name: healthz
    customHandler: healthCheckDetailed 
    pipeline:
      - pluginRef: health-check-plugin

  - name: test-context
    customHandler: contextTimeoutTest
    pipeline:
      - pluginRef: sleep-plugin
        parameters:
          duration: 5s
          
# Test the cluster health check
  - name: dr-house
    description: "Check the health of the cluster"
    pipeline:
      - pluginRef: health-check-plugin
      - pluginRef: test-print-plugin #kube-health-plugin
        parameters:
          namespace: default

  - name: alert-flow
    description: "Alert flow for health check"
    pipeline:
      - pluginRef: health-check-plugin
      - pluginRef: formatter-plugin
      - pluginRef: slack-notifier
        parameters:
          channel: "#alerts"
          severity: "high"