# Paso 1: Parsear este fichero yaml y que se guarde en un struct para acceder a los campos
logging:
  level: info
  format: json

# Paso 2: Levantar un server para probar
server:
  port: 8080
  address: 0.0.0.0

  http:
    protocolVersion: 2

  # Paso 3: Construir un plugin que se compile como .so
plugins:
  - name: slack-notifier
    path: plugins/slack/slack.so
    type: notification
    config:
      webhook_url: https://hooks.slack.com/services/TXXXXXXXX/BXXXXXXXX/XXXXXXXXXXXXXXXXX

  - name: health-check-plugin
    path: plugins/healthcheck/health_check.so
    type: health
    config: {}

  - name: sleep-plugin
    path: plugins/sleep/sleep_plugin.so
    type: test
    config: {}
 
  - name: kube-health-plugin
    path: plugins/kubehealth/kube_health.so
    type: k8s
    config: {}

  - name: test-print-plugin
    path: plugins/testprint/testprint.so
    type: test
    config: {}

  - name: clean-disk-plugin
    path: plugins/clean-disk/clean_disk.so
    type: test
    config: {}

 # Paso 4: Crear un pipeline que ejecute los plugins que se han cargado en el paso 3 y que se ejecuten en el orden que se han definido en el fichero yaml   
flows:
  - name: incident-flow
    pipeline:
      - pluginRef: slack-notifier
        parameters:
          message: "¡Alerta de prueba!"
          channel: "#alerts"
          severity: "high"

  - name: healthz
    customHandler: healthCheckDetailed 
    pipeline:
      - pluginRef: health-check-plugin

  - name: test-context
    customHandler: contextTimeoutTest
    pipeline:
      - pluginRef: sleep-plugin
        parameters:
          duration: 5s
# Test the cluster health check
  - name: dr-house
    description: "Check the health of the cluster"
    pipeline:
      - pluginRef: health-check-plugin
      - pluginRef: test-print-plugin #kube-health-plugin <--- this is a test plugin
        parameters:
          namespace: default

  - name: clean-disk-flow # working on it
    description: "Clean the disk"
    pipeline:
      - pluginRef: clean-disk-plugin
        parameters:
          namespace: default
          schedule: "@daily"
          services:
            - nginx
            - redis
          cleanupPaths:
            - /var/cache
            - /tmp
