# Paso 1: Parsear este fichero yaml y que se guarde en un struct para acceder a los campos
logging:
  level: info
  format: json

# Paso 2: Levantar un server para probar
server:
  port: 8080
  address: 0.0.0.0

  http:
    protocolVersion: 2

  # Paso 3: Construir un plugin que se compile como .so
plugins:
  - name: slack-notifier
    path: plugins/slack/slack.so
    type: notification
    config:
      webhook_url: https://hooks.slack.com/services/TXXXXXXXX/BXXXXXXXX/XXXXXXXXXXXXXXXXX

  - name: health-check-plugin
    path: plugins/healthcheck/health_check.so
    type: health
    config: {}

  - name: sleep-plugin
    path: plugins/sleep/sleep_plugin.so
    type: test
    config: {}
 
  - name: kube-health-plugin
    path: plugins/kubehealth/kube_health.so
    type: k8s
    config: {}

  - name: test-print
    path: plugins/testprint/testprint.so
    type: test
    config: {}

  - name: clean-disk
    path: plugins/clean-disk/clean_disk.so
    type: test
    config: {}

  - name: log-file-creator
    path: plugins/logfilecreator/logfilecreator.so
    type: logging
    config:
      log_path: "logs/daily"
      base_filename: "expressops-"

 # Paso 4: Crear un pipeline que ejecute los plugins que se han cargado en el paso 3 y que se ejecuten en el orden que se han definido en el fichero yaml   
flows:
  - name: incident-flow
    pipeline:
      - pluginRef: slack-notifier
        parameters:
          message: "¡Alerta de prueba!"
          channel: "#alerts"
          severity: "high"
      - pluginRef: log-file-creator
        parameters:
          plugin_name: "slack-notifier"
          plugin_output: "Alerta enviada a Slack"

  - name: healthz
    customHandler: healthCheckDetailed 
    pipeline:
      - pluginRef: health-check-plugin
      - pluginRef: log-file-creator
        parameters:
          plugin_name: "health-check-plugin"
          plugin_output: "Health check completed"

  - name: test-context
    customHandler: contextTimeoutTest
    pipeline:
      - pluginRef: sleep-plugin
        parameters:
          duration: 5s
      - pluginRef: log-file-creator
        parameters:
          plugin_name: "sleep-plugin"
          plugin_output: "Sleep operation completed"

# Test the cluster health check
  - name: dr-house
    description: "Check the health of the cluster"
    pipeline:
      - pluginRef: health-check-plugin
      - pluginRef: test-print
        parameters:
          namespace: default
      - pluginRef: log-file-creator
        parameters:
          plugin_name: "cluster-health-check"
          plugin_output: "Completed health check of all components"

  - name: clean-disk-flow 
    description: "Clean the disk"
    pipeline:
      - pluginRef: clean-disk
        parameters:
          cleanupPaths:
            - /var/cache
            - /tmp
      - pluginRef: log-file-creator
        parameters:
          plugin_name: "clean-disk"
          plugin_output: "Disk cleanup performed"
          cleanupPaths: ["/var/cache", "/tmp"]
  
  - name: daily-system-log
    description: "Create a daily log of system status"
    pipeline:
      - pluginRef: health-check-plugin
      - pluginRef: log-file-creator
        parameters:
          plugin_name: "health-check-plugin"
          plugin_output: "Daily system health check"
          base_filename: "daily-health-"
