
logging:
  level: info
  format: json


server:
  port: 8080
  address: 0.0.0.0

  http:
    protocolVersion: 2


plugins:
  - name: slack-notifier
    path: plugins/slack/slack.so
    type: notification
    config: {}
      
  - name: health-check-plugin
    path: plugins/healthcheck/health_check.so
    type: health
    config: {}

  - name: sleep-plugin
    path: plugins/sleep/sleep_plugin.so
    type: test
    config: {}
 
  - name: kube-health-plugin
    path: plugins/kubehealth/kube_health.so
    type: k8s
    config: {}

  - name: test-print-plugin
    path: plugins/testprint/testprint.so
    type: test
    config: {}

  - name: formatter-plugin
    path: plugins/formatters/health_alert_formatter.so
    type: utils
    config: {}


flows:
  - name: incident-flow
    pipeline:
      - pluginRef: slack-notifier

  - name: healthz
    customHandler: healthCheckDetailed 
    pipeline:
      - pluginRef: health-check-plugin

  - name: test-context
    customHandler: contextTimeoutTest
    pipeline:
      - pluginRef: sleep-plugin

  - name: dr-house
    description: "Check the health of the cluster"
    pipeline:
      - pluginRef: health-check-plugin
      - pluginRef: test-print-plugin

  - name: alert-flow
    description: "Alert flow for health check"
    pipeline:
      - pluginRef: health-check-plugin
      - pluginRef: formatter-plugin
      - pluginRef: slack-notifier
