logging:
  level: info
  format: json


server:
  port: 8080
  address: 0.0.0.0
  timeoutSeconds: 4

  http:
    protocolVersion: 2

plugins:
  - name: slack-notifier
    path: plugins/slack/slack.so
    type: notification
    config: {}
      
  - name: health-check-plugin
    path: plugins/healthcheck/health_check.so
    type: health
    config: {}

  - name: sleep-plugin
    path: plugins/sleep/sleep_plugin.so
    type: test
    config: {}
 
  - #name: kube-health-plugin
    #path: plugins/kubehealth/kube_health.so
    #type: k8s
    #config: {}

  - name: test-print-plugin
    path: plugins/testprint/testprint.so
    type: test
    config: {}

  - name: formatter-plugin
    path: plugins/formatters/health_alert_formatter.so
    type: utils
    config: {}
    
  - name: logfilecreator
    path: plugins/logfilecreator/logfilecreator.so
    type: utils
    config:
      log_dir: "logs"
      
  - name: logcleaner
    path: plugins/logcleaner/logcleaner.so
    type: utils
    config:
      log_dir: "logs"
      max_age_days: 30


flows:
  - name: incident-flow
    description: "Notify the team when an incident occurs" #rn only for testing
    pipeline:
      - pluginRef: slack-notifier

  - name: healthz
    description: "Health check"
    customHandler: healthCheckDetailed 
    pipeline:
      - pluginRef: health-check-plugin
      - pluginRef: formatter-plugin

  - name: test-context # sleep testing
    description: "Test the context timeout"
    customHandler: contextTimeoutTest
    pipeline:
      - pluginRef: sleep-plugin

  - name: dr-house
    description: "Check the health of the cluster"
    pipeline:
      - pluginRef: health-check-plugin
      - pluginRef: formatter-plugin
      - pluginRef: test-print-plugin # it will be kube-health-plugin in the future :D
      - pluginRef: logfilecreator

  - name: weekly-cleanup
    description: "Weekly log zip and cleanup"
    pipeline:
      - pluginRef: logcleaner

  - name: alert-flow
    pipeline:
      - pluginRef: health-check-plugin
      - pluginRef: formatter-plugin
      - pluginRef: slack-notifier
