logging:
  level: info
  format: text # bcs logger is initialized with text formatter


server:
  port: 8080
  address: 0.0.0.0
  timeoutSeconds: 4

  http:
    protocolVersion: 2

plugins:
  - name: slack-notifier
    path: plugins/slack/slack.so
    type: notification
    config:
      webhook_url: $SLACK_WEBHOOK_URL # obligatory env var
      
  - name: health-check-plugin
    path: plugins/healthcheck/health_check.so
    type: health
    config:
      thresholds:
        cpu: 90.0
        memory: 90.0
        disk: 85.0

  - name: sleep-plugin
    path: plugins/sleep/sleep_plugin.so
    type: test
    config: 
      duration_seconds: ${SLEEP_DURATION:-10}  # Sleep duration in seconds
 
  - #name: kube-health-plugin
    #path: plugins/kubehealth/kube_health.so
    #type: k8s
    #config: {}

  - name: test-print-plugin
    path: plugins/testprint/testprint.so
    type: test
    config: {}

  - name: formatter-plugin
    path: plugins/formatters/health_alert_formatter.so
    type: utils
    config:
      thresholds:
        cpu:
          warning: 50
          critical: 80
        memory:
          warning: 60
          critical: 85
        disk:
          warning: 80
          critical: 90


flows:
  - name: incident-flow
    description: "Notify the team when an incident occurs" #rn only for testing
    pipeline:
      - pluginRef: slack-notifier

  - name: healthz
    description: "Health check"
    customHandler: healthCheckDetailed 
    pipeline:
      - pluginRef: health-check-plugin
      - pluginRef: formatter-plugin

  - name: test-context # sleep testing
    description: "Test the context timeout"
    customHandler: contextTimeoutTest
    pipeline:
      - pluginRef: sleep-plugin

  - name: dr-house
    description: "Check the health of the cluster"
    pipeline:
      - pluginRef: health-check-plugin
      - pluginRef: formatter-plugin
      - pluginRef: test-print-plugin # it will be kube-health-plugin in the future :D

  - name: alert-flow
    description: "Health check with notification"
    pipeline:
      - pluginRef: health-check-plugin
      - pluginRef: formatter-plugin
      - pluginRef: slack-notifier
