apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: expressops-slack-external-secret
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: expressops-external-secrets
    kind: ClusterSecretStore
  target:
    name: expressops-slack-secret
    creationPolicy: Owner
  data:
    - secretKey: SLACK_WEBHOOK_URL
      remoteRef:
        key: projects/88527591198/secrets/slack-webhook
        version: "latest" 