apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: expressops-external-secrets
spec:
  provider:
    gcpsm:
      projectID: fc-it-school-2025
      auth:
        secretRef:
          secretAccessKeySecretRef:
            name: gcp-secret-creds
            key: sa.json 
            