#----------------------------------------
# Prometheus Integration
#----------------------------------------

## Prometheus Monitoring System
.PHONY: prometheus-install prometheus-port-forward prometheus-uninstall \
        prometheus-show-metrics grafana-install grafana-port-forward grafana-uninstall



# Install Prometheus using Helm
prometheus-install: ## Install Prometheus in Kubernetes using Helm
	@echo "Installing Prometheus in namespace $(PROMETHEUS_NAMESPACE)..."
	kubectl create namespace $(PROMETHEUS_NAMESPACE) 2>/dev/null || true
	helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
	helm repo update
	helm upgrade --install $(PROMETHEUS_RELEASE) prometheus-community/prometheus \
		--namespace $(PROMETHEUS_NAMESPACE) \
		--version $(PROMETHEUS_CHART_VERSION) \
		--set server.persistentVolume.enabled=false \
		--set alertmanager.persistentVolume.enabled=false
	@echo "Prometheus installed. To access use: make prometheus-port-forward"

# Port forwarding to access Prometheus
prometheus-port-forward: ## Access Prometheus web interface via port-forward
	@echo "Setting up port-forward for Prometheus at http://localhost:$(PROMETHEUS_PORT)"
	kubectl port-forward -n $(PROMETHEUS_NAMESPACE) svc/$(PROMETHEUS_RELEASE)-server $(PROMETHEUS_PORT):80

# Uninstall Prometheus
prometheus-uninstall: ## Uninstall Prometheus from Kubernetes
	@echo "Uninstalling Prometheus..."
	helm uninstall $(PROMETHEUS_RELEASE) -n $(PROMETHEUS_NAMESPACE)


# Install Grafana
grafana-install: ## Install Grafana with preconfigured dashboard
	@echo "Installing Grafana in namespace $(PROMETHEUS_NAMESPACE)..."
	kubectl create namespace $(PROMETHEUS_NAMESPACE) 2>/dev/null || true
	helm repo add grafana https://grafana.github.io/helm-charts
	helm repo update
	helm upgrade --install $(GRAFANA_RELEASE) grafana/grafana \
		--namespace $(PROMETHEUS_NAMESPACE) \
		--version $(GRAFANA_CHART_VERSION) \
		--set persistence.enabled=false 
	@echo "Grafana installed. To access use: make grafana-port-forward"
	@echo "Credentials: user: admin / passwd: {Generated by kubernetes}"

# Port forwarding to access Grafana
grafana-port-forward: ## Access Grafana web interface via port-forward
	@echo "Setting up port-forward for Grafana at http://localhost:$(GRAFANA_PORT)"
	kubectl port-forward -n $(PROMETHEUS_NAMESPACE) svc/$(GRAFANA_RELEASE) $(GRAFANA_PORT):80

# Uninstall Grafana
grafana-uninstall: ## Uninstall Grafana from Kubernetes
	@echo "Uninstalling Grafana..."
	helm uninstall $(GRAFANA_RELEASE) -n $(PROMETHEUS_NAMESPACE)