replicaCount: 1

image:
  repository: davidnull/expressops
  tag: 1.0.0
  pullPolicy: IfNotPresent

imagePullSecrets: [] 
nameOverride: ""
fullnameOverride: "" 

# Liveness Probe Configuration
livenessProbe:
  enabled: true
  path: /flow?flowName=all-flows
  initialDelaySeconds: 30
  periodSeconds: 30
  timeoutSeconds: 5
  successThreshold: 1
  failureThreshold: 3

# Readiness Probe Configuration
readinessProbe:
  enabled: true
  path: /flow?flowName=health-status-no-format
  initialDelaySeconds: 10
  periodSeconds: 20
  timeoutSeconds: 5
  successThreshold: 1
  failureThreshold: 3


#podSecurityContext: {}
#securityContext: {}

service:
  type: NodePort
  port: 80
  targetPort: 8080
# = rama_nacho?
resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 50m
    memory: 64Mi

env:
  SERVER_PORT: "8080"
  SERVER_ADDRESS: "0.0.0.0"
  PLUGINS_PATH: "plugins"

config:
  # Configure key application settings
  logging:
    level: info
    format: text
  server:
    timeoutSeconds: 4

# External Secrets configuration
externalSecrets:
  enabled: true
  refreshInterval: "1h"
  secretStore:
    name: "expressops-external-secrets"
    kind: "ClusterSecretStore"
  remoteRef:
    key: "projects/88527591198/secrets/slack-webhook"
    version: "latest"
    
# Google Cloud Secret Manager configuration
gcpSecretManager:
  enabled: true
  projectID: "fc-it-school-2025"
  serviceAccount: "expressops-external-secrets@fc-it-school-2025.iam.gserviceaccount.com"
  # Service account credentials should be provided during deployment
  serviceAccountKey: ""

clusterSecretStore:
  enabled: true