apiVersion: v1
kind: ConfigMap
metadata:
  name: filebeat-config
  namespace: dav-monitoring
data:
  filebeat.yml: |
    filebeat.autodiscover:
      providers:
        - type: kubernetes
          node: ${NODE_NAME}
          templates:
            - condition:
                equals:
                  kubernetes.namespace: default
              config:
                - type: container
                  paths:
                    - /var/log/containers/*-${data.kubernetes.container.id}.log
    processors:
      - add_kubernetes_metadata:
          in_cluster: true
    output.logstash:
      hosts: ["logstash.default.svc.cluster.local:5044"]
