apiVersion: v1
kind: ConfigMap
metadata:
  name: filebeat-config
  namespace: dav-monitoring
data:
  filebeat.yml: |
    filebeat.inputs:
      - type: log
        enabled: true
        paths:
          - /var/log/*.log

    output.logstash:
      hosts: ["logstash.dav-monitoring.svc.cluster.local:5044"]
