name: ExpressOps CI/CD

on:
  push:
    branches: [ master ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24'
          cache: true
      
      - name: Test
        run: go test -v ./...

  deploy:
    name: Deploy to Kubernetes
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get latest Docker Hub tag
        id: get_latest_tag
        run: |
          LATEST_TAG=$(curl -s "https://hub.docker.com/v2/repositories/davidnull/expressops/tags/" | grep -o '"name":"[^"]*' | grep -v latest | sed 's/"name":"//' | head -1)
          echo "LATEST_TAG=$LATEST_TAG" >> $GITHUB_ENV
          echo "Latest tag found: $LATEST_TAG"

      - name: Set up gcloud
        uses: google-github-actions/setup-gcloud@v1
        with:
          install_components: 'gke-gcloud-auth-plugin'

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'
          
      - name: Setup kubectl & Helm
        run: |
          # Install kubectl and helm
          curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
          chmod +x kubectl
          sudo mv kubectl /usr/local/bin/
          
          curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash

      - name: Start tunnel and deploy with Helm
        run: |
          # Crear directorio para kubeconfig
          mkdir -p ~/.kube
          
          # Start SSH tunnel in background
          echo "Starting SSH tunnel to GKE cluster..."
          nohup gcloud compute ssh --zone "europe-west1-d" "it-school-2025-1" --tunnel-through-iap --project "fc-it-school-2025" --ssh-flag "-N -L 6443:127.0.0.1:6443" &
          TUNNEL_PID=$!
          echo "Tunnel process started with PID: $TUNNEL_PID"
          
          # Wait for tunnel to establish
          sleep 10
          
          # Crear kubeconfig básico para acceder a través del túnel
          cat > ~/.kube/config <<EOF
          apiVersion: v1
          kind: Config
          clusters:
          - name: k3s-cluster
            cluster:
              server: https://localhost:6443
              insecure-skip-tls-verify: true
          contexts:
          - name: k3s
            context:
              cluster: k3s-cluster
              user: admin
          current-context: k3s
          users:
          - name: admin
            user: {}
          EOF
          
          # Verify we can connect
          kubectl get nodes || (echo "Failed to connect to cluster" && kill $TUNNEL_PID && exit 1)
          
          # Deploy with Helm
          echo "Deploying with latest image tag: $LATEST_TAG"
          helm upgrade --install expressops ./helm \
            --namespace default \
            -f ./helm/values.yaml \
            --set image.tag=$LATEST_TAG \
            --create-namespace

          kill $TUNNEL_PID 

