name: ExpressOps CI/CD

on:
  push:
    branches: [ puesta_en_conjunto ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ puesta_en_conjunto ]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24'
          cache: true
      
      - name: Test
        run: go test -v ./...

  deploy:
    name: Deploy to Kubernetes
    if: github.event_name == 'push' && github.ref == 'refs/heads/puesta_en_conjunto'
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get latest Docker Hub tag
        id: get_latest_tag
        run: |
          LATEST_TAG=$(curl -s "https://hub.docker.com/v2/repositories/davidnull/expressops/tags/" | grep -o '"name":"[^"]*' | grep -v latest | sed 's/"name":"//' | head -1)
          echo "LATEST_TAG=$LATEST_TAG" >> $GITHUB_ENV

      - name: Prepare service account key
        run: |
          mkdir -p ./credentials
          echo '${{ secrets.GCP_SA_KEY }}' > ./credentials/key.json
          chmod 600 ./credentials/key.json
        
      # Empaquetar y copiar el chart de Helm a la VM remota
      - name: Package Helm Chart
        run: |
          tar -czf expressops-chart.tar.gz ./helm
        
      - name: Deploy using gcloud SSH
        run: |
          docker run --rm \
            -v $(pwd):/workspace \
            -v $(pwd)/credentials:/gcp-key \
            -e GOOGLE_APPLICATION_CREDENTIALS=/gcp-key/key.json \
            -w /workspace \
            google/cloud-sdk:latest bash -c '
              # Autenticarse con GCP
              gcloud auth activate-service-account --key-file=/gcp-key/key.json
              gcloud config set project fc-it-school-2025
              
              # Copiar el chart empaquetado a la VM
              gcloud compute scp --zone "europe-west1-d" \
                expressops-chart.tar.gz it-school-2025-1:/tmp/ \
                --tunnel-through-iap \
                --project "fc-it-school-2025"
              
              # Ejecutar comando Helm directamente en la VM remota
              gcloud compute ssh it-school-2025-1 --zone "europe-west1-d" \
                --tunnel-through-iap \
                --project "fc-it-school-2025" \
                --command "
                  # Desempaquetar el chart
                  mkdir -p /tmp/expressops-chart
                  tar -xzf /tmp/expressops-chart.tar.gz -C /tmp/expressops-chart
                  
                  # Ejecutar Helm desde dentro de la VM
                  helm upgrade --install expressops /tmp/expressops-chart/helm \
                    --namespace default \
                    -f /tmp/expressops-chart/helm/values.yaml \
                    --set image.tag=${{ env.LATEST_TAG }} \
                    --create-namespace
                  
                  # Limpiar
                  rm -rf /tmp/expressops-chart.tar.gz /tmp/expressops-chart
                "
            '
