# IGNORE THIS
# NOT WORKING, NOT FUNCTIONAL, JUST TO LEARN
#============================================
#   ...
#  (ยบ-ยบ)
#    I _{cooking...}
#   \I/
#   /-\
#============================================
